alter table QUARIUM_CHECKLIST add constraint FK_QUARIUM_CHECKLIST_ON_TEST_RUN foreign key (TEST_RUN_ID) references QUARIUM_TEST_RUN(ID);
create index IDX_QUARIUM_CHECKLIST_ON_TEST_RUN on QUARIUM_CHECKLIST (TEST_RUN_ID);
