alter table QUARIUM_TEST_RUN add constraint FK_QUARIUM_TEST_RUN_ON_MILESTONE foreign key (MILESTONE_ID) references QUARIUM_MILESTONE(ID);
create index IDX_QUARIUM_TEST_RUN_ON_MILESTONE on QUARIUM_TEST_RUN (MILESTONE_ID);
