alter table QUARIUM_MILESTONE add constraint FK_QUARIUM_MILESTONE_ON_PROJECT foreign key (PROJECT_ID) references QUARIUM_PROJECT(ID);
create index IDX_QUARIUM_MILESTONE_ON_PROJECT on QUARIUM_MILESTONE (PROJECT_ID);
