alter table QUARIUM_PROJECT add constraint FK_QUARIUM_PROJECT_ON_THESIS_VERSION foreign key (THESIS_VERSION_ID) references QUARIUM_THESIS_VERSION(ID);
create index IDX_QUARIUM_PROJECT_ON_THESIS_VERSION on QUARIUM_PROJECT (THESIS_VERSION_ID);
