alter table QUARIUM_PROJECT add constraint FK_QUARIUM_PROJECT_ON_VERSION_OF foreign key (VERSION_OF_ID) references QUARIUM_PROJECT(ID);
create index IDX_QUARIUM_PROJECT_ON_VERSION_OF on QUARIUM_PROJECT (VERSION_OF_ID);
