alter table QUARIUM_CASE_RESULT add constraint FK_QUARIUM_CASE_RESULT_ON_TEST_CASE foreign key (TEST_CASE_ID) references QUARIUM_TEST_CASE(ID);
create index IDX_QUARIUM_CASE_RESULT_ON_TEST_CASE on QUARIUM_CASE_RESULT (TEST_CASE_ID);
