alter table QUARIUM_CHECKLIST add constraint FK_QUARIUM_CHECKLIST_ON_PARENT_CARD foreign key (PARENT_CARD_ID) references QUARIUM_CHECKLIST(ID);
create index IDX_QUARIUM_CHECKLIST_ON_PARENT_CARD on QUARIUM_CHECKLIST (PARENT_CARD_ID);
