alter table QUARIUM_CHECKLIST add constraint FK_QUARIUM_CHECKLIST_ON_STATE foreign key (STATE_ID) references QUARIUM_STATEMENT(ID);
create index IDX_QUARIUM_CHECKLIST_ON_STATE on QUARIUM_CHECKLIST (STATE_ID);
