alter table QUARIUM_CHECKLIST add constraint FK_QUARIUM_CHECKLIST_ON_ASSIGNED_QA foreign key (ASSIGNED_QA_ID) references QUARIUM_QA_PROJECT_RELATIONSHIP(ID);
create index IDX_QUARIUM_CHECKLIST_ON_ASSIGNED_QA on QUARIUM_CHECKLIST (ASSIGNED_QA_ID);
