alter table QUARIUM_MODULE add constraint FK_QUARIUM_MODULE_ON_PROJECT foreign key (PROJECT_ID) references QUARIUM_PROJECT(ID);
create index IDX_QUARIUM_MODULE_ON_PROJECT on QUARIUM_MODULE (PROJECT_ID);
