alter table QUARIUM_CHECKLIST add constraint FK_QUARIUM_CHECKLIST_ON_SUB_CARD foreign key (SUB_CARD_ID) references QUARIUM_CHECKLIST(ID);
create index IDX_QUARIUM_CHECKLIST_ON_SUB_CARD on QUARIUM_CHECKLIST (SUB_CARD_ID);
