alter table QUARIUM_TEST_CASE add constraint FK_QUARIUM_TEST_CASE_ON_STATE foreign key (STATE_ID) references QUARIUM_STATEMENT(ID);
create index IDX_QUARIUM_TEST_CASE_ON_STATE on QUARIUM_TEST_CASE (STATE_ID);
