alter table QUARIUM_CHECKLIST add constraint FK_QUARIUM_CHECKLIST_ON_MODULE foreign key (MODULE_ID) references QUARIUM_MODULE(ID);
create index IDX_QUARIUM_CHECKLIST_ON_MODULE on QUARIUM_CHECKLIST (MODULE_ID);
