alter table QUARIUM_CHECKLIST add constraint FK_QUARIUM_CHECKLIST_ON_ASSIGNED_QA foreign key (ASSIGNED_QA_ID) references QUARIUM_QA_PROJECT_RELATIONSHIP(ID);
alter table QUARIUM_CHECKLIST add constraint FK_QUARIUM_CHECKLIST_ON_STATE foreign key (STATE_ID) references QUARIUM_STATEMENT(ID);
alter table QUARIUM_CHECKLIST add constraint FK_QUARIUM_CHECKLIST_ON_PROJECT foreign key (PROJECT_ID) references QUARIUM_PROJECT(ID);
create index IDX_QUARIUM_CHECKLIST_ON_ASSIGNED_QA on QUARIUM_CHECKLIST (ASSIGNED_QA_ID);
create index IDX_QUARIUM_CHECKLIST_ON_STATE on QUARIUM_CHECKLIST (STATE_ID);
create index IDX_QUARIUM_CHECKLIST_ON_PROJECT on QUARIUM_CHECKLIST (PROJECT_ID);
