alter table QUARIUM_CHECKLIST add constraint FK_QUARIUM_CHECKLIST_ON_PROJECT foreign key (PROJECT_ID) references QUARIUM_PROJECT(ID);
create index IDX_QUARIUM_CHECKLIST_ON_PROJECT on QUARIUM_CHECKLIST (PROJECT_ID);
