alter table QUARIUM_CHECKLIST add constraint FK_QUARIUM_CHECKLIST_ON_REGRESS_PROJECT foreign key (REGRESS_PROJECT_ID) references QUARIUM_PROJECT(ID);
create index IDX_QUARIUM_CHECKLIST_ON_REGRESS_PROJECT on QUARIUM_CHECKLIST (REGRESS_PROJECT_ID);
