alter table QUARIUM_QA_PROJECT_RELATIONSHIP add constraint FK_QUARIUM_QA_PROJECT_RELATIONSHIP_ON_QA foreign key (QA_ID) references QUARIUM_QA(ID);
create index IDX_QUARIUM_QA_PROJECT_RELATIONSHIP_ON_QA on QUARIUM_QA_PROJECT_RELATIONSHIP (QA_ID);
